"use client"; //just for testing
import { useEffect } from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import TopBar from "@/components/TopBar";
import Sidebar from "@/components/Sidebar";

// const Comic_sans_MS = localFont({
//   src: [
//     {
//       path: "/fonts/COMIC.TTF",
//       style: "normal",
//     },
//     {
//       path: "/fonts/COMICBD.TTF",
//       style: "normal",
//       weight: "bold"
//     },
//     {
//       path: "/fonts/COMICI.TTF",
//       style: "italic",
//     },
//     {
//       path: "/fonts/COMICZ.TTF",
//       style: "italic",
//       weight: "bold",
//     }
//   ],
//   variable: "--font-comic-sans",
// });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    localStorage.setItem("role", "admin"); // Change to 'user' / 'admin' for testing
    document.cookie = `role=${localStorage.getItem("role")}; path=/; secure; samesite=lax`;
  }, []);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >      
        <Sidebar/> 
        <TopBar/>
        
        {children}
      </body>
    </html>
  );
}
